### ISSUE TITLE
将项目fork下来后，导入jar包后启动报错

### ISSUE THREAD

**Issue by YWS66** [xuanbo/fine-report-10#2]
**帆软报表jar包版本2020年9月份最新版，项目启动后报**
Caused by: java.lang.ClassNotFoundException: org.springframework.jdbc.CannotGetJdbcConnectionException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	... 20 common frames omitted
以及
Caused by: javax.management.InstanceAlreadyExistsException: DefaultDomain:application=
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.springframework.context.support.LiveBeansView.registerApplicationContext(LiveBeansView.java:79)
	... 10 common frames omitted

**Comment by jwjkr** [comment]
我也一样报这样的错，搞不明白了。

**Comment by jwjkr** [comment]
我运行jar包确实运行起来了，但在idea中运行不了，无法debug啊！
